### ISSUE TITLE
Does taskctl support capturing output from called apps and storing as a variable?

### ISSUE THREAD

**Issue by atc0005** [taskctl/taskctl#54]
Hi,

I'm exploring using this tool as a potential replacement for Makefiles in some of my projects (Go newbie). One of the features I'm looking for is calling external applications and capturing their output for use with various tasks. For example, capturing the current commit hash so I can pass it to `go build` via a `-ldflags` option.

I looked over the README and the [Full config example](https://github.com/taskctl/taskctl/blob/master/docs/example.yaml), but didn't see this mentioned. It could very well be there and I have just overlooked it.

If this isn't supported now, is it a planned feature?

Thank you for your time.

**Comment by trntv** [comment]
Not yet. But it have everything to implement it in next release.
