### ISSUE TITLE
Segmentation violation

### ISSUE THREAD

**Issue by CompuRoot** [taskctl/taskctl#72]
Unpack `taskctl` to an empty directory that unavailable via PATH and try to run it.
Program failed to start with following error message:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x875685]

goroutine 1 [running]:
main.buildTaskRunner(0xc0001a0580, 0xc0001961c8, 0x96a119, 0x412822)
	/home/runner/work/taskctl/taskctl/cmd/taskctl/taskctl.go:254 +0x75
main.rootAction(0xc0001a0580, 0xc00019e800, 0x0)
	/home/runner/work/taskctl/taskctl/cmd/taskctl/taskctl.go:194 +0x43
github.com/urfave/cli/v2.(*App).RunContext(0xc000082780, 0xa2cba0, 0xc0000b6010, 0xc0000961b0, 0x1, 0x1, 0x0, 0x0)
	pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x70b
github.com/urfave/cli/v2.(*App).Run(...)
	pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.run(0xc0000c4000, 0xa23680)
	/home/runner/work/taskctl/taskctl/cmd/taskctl/taskctl.go:67 +0xa7
main.main()
	/home/runner/work/taskctl/taskctl/cmd/taskctl/taskctl.go:43 +0x73
```
The reason is absents of `yaml` file. After running `taskctl init` to create default config, everything is fine then.

My suggestion is to throw human understandable error, something like: `Can't run due to absents of config file. Run taskctl init to create default one`

**Comment by trntv** [comment]
hmm, I think we should just do nothing, no error should appear in this case. The reason why taskctl should run if no config file present in current directory is that there is global config file, where global tasks live. I'll fix this error. Thank you.
