### ISSUE TITLE
Command line arguments should be available as an array / slice

### ISSUE THREAD

**Issue by hetesiistvan** [taskctl/taskctl#80]
Provided command line arguments are available now as a string in the ```.Args``` variable.

Handling individual arguments is somewhat inconvenient this way.

# Feature request

Would be nice if the command line arguments would be available as an array / slice to reach individual arguments more conveniently.

E.g. provided by this command line ```taskctl mytask -- arg1 arg2```
We could reach the values like ```.Argsa[0]``` which would equal ```arg1```

Thanks for considering this request!

**Comment by trntv** [comment]
Hi, your feature request sounds reasonable enough to implement. I'm not yet sure about possible naming but I'll try to implement it as quick as possible. 

Thank you for your participation!

**Comment by hetesiistvan** [comment]
Thank you very much for the quick response, much appreciated!

If you need a hand for (manual) testing the new feature just let me know!

**Comment by trntv** [comment]
```yaml
lint:
  command: go lint {{index .ArgsList 0}}
```
