### ISSUE TITLE
Output property is ignored when specified in the tasks.yml file

### ISSUE THREAD

**Issue by hetesiistvan** [taskctl/taskctl#83]
Just like in the documentation [1] I specify the ```output``` property in the ```tasks.yml``` file:
```yaml
output: prefixed
```

Unfortunately it seems to be ignored by ```taskctl```. When I specify this option via command line (```-o prefixed```) then it works just as expected.

I use ```taskctl``` on macOsx, the version is:
```shell
$ taskctl -version
taskctl version 1.3.0
```

Am I doing something incorrectly?

Thanks for checking in advance!

[1] - https://github.com/taskctl/taskctl/blob/master/docs/example.yaml#L163

**Comment by trntv** [comment]
Fixed, thank you for reporting!
